#!/usr/bin/env bash
set -eEu
set -o pipefail

################################################################################
# Bootstrap the user DevEnv.
################################################################################
. sdlc/functions.sh

if ! git remote show upstream &>/dev/null; then
    # This is necessary for gitlint.
    git remote add upstream https://github.com/jumanjihouse/foal.git
fi
git fetch --all --prune

"${PIP}" install --user -r sdlc/requirements.txt
pre-commit install-hooks -c sdlc/pre-commit-config.yaml

touch sdlc/.bootstrap
