---
# This file contains pre-commit hooks that I choose not to use.

repos:
    # Like reorder-python-imports.
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort

    # Black optimizes format over diff churn.
    # Some of its opinions are great. Others suck.
    # Example:
    #
    # -    package_data={
    # -        "": ["data/*.yaml"],
    # -    },
    # -    entry_points={
    # -        "console_scripts": [
    # -            "foal=foal.__main__:main",
    # -        ],
    # -    },
    # -    install_requires=[
    # -        "identify>=1.4.18, <2",
    # -        "ruamel.yaml>=0.16.10, <1",
    # -    ],
    # +    package_data={"": ["data/*.yaml"],},
    # +    entry_points={"console_scripts": ["foal=foal.__main__:main",],},
    # +    install_requires=["identify>=1.4.18, <2", "ruamel.yaml>=0.16.10, <1",],
    #
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
