---
# Config for https://pre-commit.com/

################################################################################
#    Check sdlc/pre-commit-hooks-rejects.yaml before you add one here.
################################################################################
fail_fast: false
repos:
    - repo: https://github.com/frnmst/md-toc
      rev: 7.0.2
      hooks:
          - id: md-toc
            args: [-p, --skip-lines, '1', commonmarker]

    - repo: https://github.com/codespell-project/codespell
      rev: v1.17.1
      hooks:
          - id: codespell

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.23.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-added-large-files
          - id: check-builtin-literals
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
            exclude: foal/__main__.py
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-vcs-permalinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: pretty-format-json
          - id: requirements-txt-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
          - id: mypy

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.5.1
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: text-unicode-replacement-char

    - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
      rev: v0.3.3
      hooks:
          - id: pep257

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.4.4
      hooks:
          - id: pyupgrade

    # Like isort, but more static.
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.0
      hooks:
          - id: reorder-python-imports

    # WARN: This hook ignores some pep8 options for closing brace.
    # https://github.com/asottile/add-trailing-comma/blob/4737c82ee/add_trailing_comma.py#L348-L357
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma

    - repo: https://github.com/asottile/yesqa
      rev: v1.1.0
      hooks:
          - id: yesqa

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.7
      hooks:
          - id: forbid-crlf
          - id: forbid-tabs
            exclude_types:  # Types come from "identify-cli".
                - makefile
                - go

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.13.1
      hooks:
          - id: gitlint
            stages: [commit-msg]
          - id: gitlint
            entry: gitlint --commits origin/master..
            exclude: .*
            always_run: true
            stages: [manual]

    - repo: https://github.com/Yelp/detect-secrets
      rev: v0.13.1
      hooks:
          - id: detect-secrets
            args: [--baseline, sdlc/secrets.baseline]

    - repo: https://github.com/thoughtworks/talisman
      rev: v1.2.0
      hooks:
          - id: talisman-commit

    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
          - id: bandit

    - repo: https://github.com/PyCQA/pydocstyle
      rev: 5.0.2
      hooks:
          - id: pydocstyle

    - repo: https://github.com/PyCQA/pylint
      rev: pylint-2.5.0
      hooks:
          - id: pylint
            additional_dependencies:
                # These need to match sdlc/requirements.txt
                - identify==1.4.18
                - ruamel.yaml==0.16.10

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.3
      hooks:
          - id: autopep8

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.2
      hooks:
          - id: flake8

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.13.1
      hooks:
          - id: gitlint
            stages: [commit-msg]

          - id: gitlint
            entry: gitlint --commits upstream/master..
            exclude: .*
            always_run: true
            stages: [manual]

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.0
      hooks:
          - id: check-mailmap
          - id: forbid-binary
            exclude: assets/.*
          - id: git-check  # Configure in .gitattributes
          - id: require-ascii
          - id: markdownlint
          - id: script-must-have-extension
          - id: script-must-not-have-extension
          - id: shellcheck
          - id: shfmt
          - id: git-dirty  # Configure in .gitignore
